game: Cell.o CellView.o CommandReader.o Event.o Field.o FieldView.o Game.o main.o Mediator.o Player.o
	g++ -o game Cell.o CellView.o CommandReader.o Event.o Field.o FieldView.o Game.o main.o Mediator.o Player.o

Cell.o:
	g++ -c Cell.cpp
CellView.o:
	g++ -c CellView.cpp
CommandReader.o:
	g++ -c CommandReader.cpp
Event.o:
	g++ -c Event.cpp
Field.o:
	g++ -c Field.cpp
FieldView.o:
	g++ -c FieldView.cpp
Game.o:
	g++ -c Game.cpp
main.o:
	g++ -c main.cpp
Mediator.o:
	g++ -c Mediator.cpp
Player.o:
	g++ -c Player.cpp

clean:
	rm *.o game